[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.16.1" }
serde = "1.0"
clap = "4.0"
log = "0.4"
env_logger = "0.10"
